### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leamare** [leamare/endless-nyan#1]
- [x] websocket server
  - [x] start new session (connect) // ss
    - generate session UID, device UID
  - [x] join existing session (disconnect on disconnect/timeout) // ss:1234
    - join by UID or start new session
  - [x] ping
  - [x] SERVER
    - [x] SERVER prepare // ss:1234:2345:rdy
    - [x] SERVER start // ss:1234:2345:sta
    - [x] SERVER new client joined session // join:1234:2345
  - [x] CLIENT
    - [x] started movement
    - [x] approaching limit - prepare // ss:1234:2345:pr
    - [x] hit edge // ss:1234:2345:ed
    - [x] hidden // ss:1234:2345:hd
    - [x] session settings (nyan cat ID, environment ID)
    - [x] end session
- [x] html page
  - [x] static gif bg
  - [x] Create or connect
  - [x] set nyan type
  - [x] when joined/started session:
    - [x] nyan start running jingle
    - [x] music fade in/out, bg and cat movement
    - [x] rainbow with fadeout
    - [ ] nyaned for N secs
