### ISSUE TITLE
Custom Runners

### ISSUE THREAD

**Issue by leamare** [leamare/endless-nyan#13]
Combined issue for all custom runners
- [x] Sonic Runner (Green Hill, maybe mania encore color pallete) #12
- [x] SPAAAAAAACE Core Portal 2 #11 
- [x] Pusheen donut runner #10
- [x] Marisa Kirisame

Require additional artwork:
- [x] Dota 2 Spectre (Spectre pixel art, dota bg pixel art) #7
- [ ] Dota 2 Flying Courier pixel art (and dota bg) #6 

Maybe?
- [ ] Tac Nayn #9 
- [ ] Megumin #8
